#!/bin/sh

if [ "$1" = "" ] ; then
    echo 'USAGE: pushhack <CS username>'
elif git push ; then
    ssh $1@glados.cs.rit.edu 'cd /home/stu3/s5/slb1566/Courses/242/proj-repo
    find . -type d -exec chmod 770 {} \; 2> /dev/null
    find . -type f -exec chmod 660 {} \; 2> /dev/null'
else
    echo FATAL\: git commit failed\!
fi
